### ISSUE TITLE
[Bug] queryParam store not updating the url when url.searchParams is used in server.ts

### ISSUE THREAD

**Issue by hazre** [paoloricciuti/sveltekit-search-params#12]
I've encountered a weird behavior where if im getting any data from the url params on the server, I can't update it at all on the page.

Once I remove the url.searchParams.get() methods, it starts working again, it's very odd..

here's a reproduction
https://stackblitz.com/edit/sveltejs-kit-template-default-zzzvcz

**Comment by paoloricciuti** [comment]
Thanks for reporting this...in 1.0 there are 2 goto...one for the actual update of the url and one just to add the history entry. Apparently this was mess things up when the url was accessed in the server 🤷 

I fixed it in 1.0.1, let me know if the issue is solved otherwise i'll reopen this issue.

**Comment by paoloricciuti** [comment]
I've published the package but it still doesn't fix the issue...i was having some problem with stackblitz and i tought i fixed it....reopening this now, i'll work on this later.

**Comment by hazre** [comment]
I just tested it in my local environment and still no luck on v1.0.2

**Comment by paoloricciuti** [comment]
Yes unfortunately I was having some issues on stackblitz and that made me think I fixed the issue but it is still there. Btw if you don't care about history entries you can disable history and that will fix this issue for the moment. I'll try to fix this tomorrow.

**Comment by paoloricciuti** [comment]
Ok third time the charm...this should be fixed on 1.0.3. I've verified on your repro and seem to be ok.

Closing this and hopefully i don't need to reopen it. Let me know if it's ok on your part (also i've opened an issue on the sveltekit repo)

**Comment by hazre** [comment]
I just tried it in my local environment and it works perfectly now. Thanks for the quick fix 😁

**Comment by paoloricciuti** [comment]
This is kinda of a work around and hopefully it will be fixed on the sveltekit side. Glad to help and thank to you for reporting.

**Comment by pke** [comment]
I think I have encountered the same problem. I had a call to URLSearchParams of $page in my code and the URL updating did not work. When I removed that call it started to work. What is the reason for this?

**Comment by pke** [comment]
I still can't get it to work, to calculate a reactive value based on the query param:

````ts
const length = queryParam("length", ssp.number(12));
$: (result = calc({ length: $length});
```

Here, as soon as I add the calculation, the URL stops updating and the result stays empty.

**Comment by paoloricciuti** [comment]
Would you please open a new issue and provide a minimal reproduction? Thanks ;)
